-- Catalog seeds. Keep ids aligned with lib/catalog.ts.
insert into public.seeds (id, title, description, prompt, category, kind, timeframe, waypoints) values
  ('walk-unknown', 'Walk a street you don''t know', 'A small adventure that asks nothing of anyone else.', 'Choose a neighborhood you always pass through. Walk it slowly for forty minutes. Notice one thing you would tell a friend.', 'adventure', 'practice', 'An afternoon', array['solo-among-others']),
  ('ticket-for-one', 'Buy a ticket for one', 'Stop waiting for a date that makes the outing make sense.', 'Book something small that happens this month: a train, a film, a talk. Go alone on purpose.', 'adventure', 'practice', 'One outing', array['emotional-clarity', 'solo-among-others']),
  ('local-yes', 'Say yes to a listing', 'One local yes, even if nobody else''s calendar is free.', 'Pick one local event you would usually skip because no one else is free. Put it on the calendar.', 'adventure', 'practice', 'This week', array['solo-among-others']),
  ('weekly-hello', 'A weekly hello', 'One person. One recurring note. No performance.', 'Choose one person and a small recurring check-in. Support, accountability, mutual, empowerment. Nothing more elaborate than showing up.', 'connection', 'same', 'Weekly', array['solo-among-others', 'independence-lab']),
  ('neighbor', 'A conversation without an agenda', 'Be a person in the world for a few minutes.', 'Speak to someone nearby with no plan to become friends. Just be there.', 'connection', 'practice', 'Once', array['solo-among-others']),
  ('skill-swap', 'Trade a skill', 'Offer what you know. Ask for what you have been postponing.', 'Offer something you know well enough to share for an hour. Ask for something you have been waiting to learn.', 'connection', 'skill-swap', 'One exchange', array['solo-among-others', 'independence-lab']),
  ('imperfect-making', 'Make something imperfect', 'An hour of making that is not for praise.', 'Spend an hour making something you will not show for approval.', 'creativity', 'practice', 'An hour', array['emotional-clarity']),
  ('museum-sentence', 'Leave with one sentence', 'Stay in a room until language arrives.', 'Visit a museum, a gallery, or even a shop window with real attention. Stay until one sentence arrives.', 'creativity', 'practice', 'An outing', array['solo-among-others', 'emotional-clarity']),
  ('orange-corner', 'Change one corner', 'The room does not have to wait for a different life.', 'Paint, move, or dress one corner of home in a color you have been waiting to deserve. Orange is allowed.', 'creativity', 'practice', 'A weekend hour', array['independence-lab']),
  ('morning-system', 'One system that makes morning kinder', 'Not a new personality. One kinder setup.', 'Design a single tiny home system and use it for seven days.', 'home', 'practice', 'One week', array['independence-lab']),
  ('meal-for-you', 'Cook the meal you were saving', 'Stop reserving the good meal for company.', 'Make a meal you usually postpone until someone else is there. Set a place. Eat it while it is hot.', 'home', 'practice', 'An evening', array['independence-lab']),
  ('room-for-this-life', 'Arrange the room for the life you have', 'Let the furniture tell the truth.', 'Move one piece of furniture so the room fits how you actually live.', 'home', 'practice', 'An afternoon', array['independence-lab', 'emotional-clarity']),
  ('first-hour', 'The first hour of a postponed skill', 'You do not need a plan for the whole craft.', 'Learn only the first hour of something you have been waiting to start properly.', 'growth', 'practice', 'One hour', array['emotional-clarity']),
  ('unsent-letter', 'Write the unsent letter', 'A private conversation with the part of you that keeps waiting.', 'Write to the version of you who keeps waiting. You do not have to send it.', 'growth', 'practice', 'An evening', array['emotional-clarity']),
  ('one-witness', 'One goal, one witness', 'A goal with a person beside it, not a scoreboard.', 'Name a goal that matters this month. Ask one person to witness it with you.', 'growth', 'same', 'This month', array['emotional-clarity', 'independence-lab']),
  ('table-for-one', 'A table with good light', 'A meal out that is the plan, not the waiting room.', 'Eat one meal out, alone, somewhere with kind light. Stay for the whole meal.', 'wellbeing', 'practice', 'One meal', array['solo-among-others']),
  ('walk-no-podcast', 'A walk with no soundtrack', 'Let the day be slightly ordinary.', 'Walk for thirty minutes without headphones.', 'wellbeing', 'practice', 'Thirty minutes', array['emotional-clarity']),
  ('phone-in-another-room', 'An evening in another room from your phone', 'Give one evening back to your hands.', 'Put your phone in another room for one evening.', 'wellbeing', 'practice', 'One evening', array['independence-lab', 'emotional-clarity'])
on conflict (id) do nothing;
