<?php

declare(strict_types=1);

function copy_defaults(): array
{
    static $all = null;
    if ($all === null) {
        $json = file_get_contents(__DIR__ . '/defaults.json');
        $decoded = json_decode($json ?: '', true);
        $all = is_array($decoded) ? $decoded : [];
    }
    return $all;
}

function site_text(string $key): string
{
    $defaults = copy_defaults();
    if (!array_key_exists($key, $defaults)) {
        static $logged = [];
        if (!isset($logged[$key])) {
            $logged[$key] = true;
            error_log('Go Solo content key is missing from defaults: ' . $key);
        }
    }
    $default = isset($defaults[$key]) ? (string) $defaults[$key] : '';
    $value = setting($key, $default);
    $earlier = [
        'footer_line' => [
            'A chair is here if you want it. Take your time.',
            'A calm home for people building meaningful lives on their own terms.',
        ],
        'about_founder_heading' => [
            "Hi, I'm Marge.",
        ],
        'about_hello_body' => [
            'Go Solo is intentionally founder-led. If you have a question, an idea, or simply want to say hello, I would love to hear from you.',
        ],
        'contact_body' => [
            "Hi there, nice to hear from you.\n\nIf you have ideas, questions, concerns, or stories, I'd love to hear from you.\n\nYou can reach me by writing a note.",
        ],
        'hero_subhead' => [
            "Your life doesn't have to wait",
        ],
        'hero_support' => [
            'A calm place to plant a seed, learn something, or ask for help.',
            'Go Solo helps people build meaningful lives on their own terms',
        ],
        'hero_secondary' => [
            'Learn More',
        ],
        'out_there_empty' => [
            'Out There is where members share real-world experiences and what they learned from them.',
        ],
        'campfire_empty' => [
            "Campfire is where members talk about questions, experiences, everyday life, and the things they're figuring out.",
        ],
        'garden_bio' => ['Bio'],
        'label_bio' => ['Bio'],
        'empty_bio' => ['A few words can wait.'],
        'garden_similar' => ['Someone on a similar path'],
        'garden_match' => ['A steward suggested {name} for this stretch. You can take your time.'],
        'garden_skill_match' => ['A steward connected you with {name} for a skill swap. You can take your time.'],
        'life_intro_fit' => ['It was not quite the right fit.'],
        'home_same_body' => ['Someone on a similar path. A steward can introduce you. There is no rush.'],
        'seeds_same_body' => [
            'Looking for someone on a similar stretch? A steward can introduce you. There is no score, and there is no rush.',
            'You can be open to someone on a similar stretch. A steward suggests a match. You can take your time.',
        ],
        'talk_because' => ['You were introduced because'],
    ];
    if (isset($earlier[$key]) && in_array($value, $earlier[$key], true)) {
        return $default;
    }
    return $value;
}

function site_line(string $key, array $swap = []): string
{
    $text = site_text($key);
    foreach ($swap as $name => $value) {
        $text = str_replace('{' . $name . '}', (string) $value, $text);
    }
    return $text;
}

function site_lines(string $key): array
{
    $lines = preg_split("/\r\n|\n|\r/", site_text($key)) ?: [];
    $clean = [];
    foreach ($lines as $line) {
        $line = trim($line);
        if ($line !== '') {
            $clean[] = $line;
        }
    }
    return $clean;
}

function content_anchor(string $group): string
{
    $anchor = strtolower($group);
    $anchor = preg_replace('/[^a-z0-9]+/', '-', $anchor) ?? 'group';
    return trim($anchor, '-') ?: 'group';
}

// Visible copy belongs in this registry, with a default in defaults.json.
// A new public sentence should be added here so the steward can edit it.
// Leave a string in a template only when it is security, database, or steward-desk internal text.
function content_groups(): array
{
    return [
        'Homepage' => [
            'hero_title' => 'Hero title',
            'hero_subhead' => 'Second line',
            'hero_support' => 'Supporting line',
            'hero_philosophy' => 'Philosophy line',
            'freedom_heading' => 'Freedom heading',
            'freedom_body' => 'Freedom text',
            'how_title' => 'How it works heading',
            'home_seeds_title' => 'Seeds heading',
            'home_seeds_line' => 'Seeds line',
            'home_same_title' => 'SAME card title',
            'home_same_body' => 'SAME card text',
            'home_skill_title' => 'Skill Swap card title',
            'home_skill_body' => 'Skill Swap card text',
            'home_reading_intro' => 'Reading room line',
            'home_contact_line' => 'Contact line',
        ],
        'Seeds' => [
            'seeds_title' => 'Title',
            'seeds_line' => 'Line under the title',
            'seeds_support' => 'Support line',
            'seeds_accountability' => 'Accountability line',
            'seeds_learning' => 'Learning line',
            'seeds_small' => 'Small line',
            'seeds_same_title' => 'SAME title',
            'seeds_same_meaning' => 'SAME meaning',
            'seeds_same_body' => 'SAME text',
            'seeds_support_heading' => 'Support heading',
            'seeds_examples_label' => 'Examples label',
            'seeds_skill_title' => 'Skill Swap title',
            'seeds_skill_body' => 'Skill Swap text',
            'seeds_skill_heading' => 'Skill Swap examples heading',
            'seeds_skill_examples' => 'Skill examples, one per line',
            'seeds_growing_title' => 'Growing heading',
            'seeds_growing_label' => 'What you are growing',
            'seeds_look' => 'Guest look-around',
            'seeds_join_rest' => 'Guest plant line',
            'seeds_similar_title' => 'Similar path heading',
            'seeds_similar_body' => 'Similar path text',
            'seeds_match_ready' => 'Introduction is ready',
            'seeds_asked' => 'Introduction asked',
            'seeds_company_label' => 'Company question',
            'seeds_with' => 'Already with this seed',
            'seeds_kind_practice' => 'Practice seed label',
            'board_offers' => 'Offers heading',
            'board_requests' => 'Requests heading',
            'board_add' => 'Add yours heading',
            'board_would' => 'I would like to',
            'board_offer' => 'Offer help',
            'board_ask' => 'Ask for help',
            'board_about' => 'A little about it',
        ],
        'Campfire' => [
            'campfire_title' => 'Title',
            'campfire_form_title' => 'Composer heading',
            'campfire_prompt' => 'Composer prompt',
            'campfire_body_label' => 'Writing label',
            'campfire_around' => 'Replies heading',
            'campfire_reply_label' => 'Reply label',
            'campfire_resting' => 'Resting note',
            'campfire_hidden' => 'Hidden note',
        ],
        'Waypoints' => [
            'waypoints_title' => 'Title',
            'waypoints_intro' => 'Introduction',
            'waypoints_sit_label' => 'People sit with',
            'waypoints_food_title' => 'Food for Thought heading',
            'waypoints_food_intro' => 'Food for Thought introduction',
            'waypoints_discussions_title' => 'Discussions heading',
            'waypoints_start_title' => 'Start heading',
            'waypoints_discussion_label' => 'Discussion writing label',
            'waypoints_discussion_prompt' => 'Default discussion prompt',
            'waypoints_reply_label' => 'Reply label',
            'waypoints_in_chair' => 'Inside a discussion',
            'waypoints_resting' => 'Resting note',
            'waypoints_hidden' => 'Hidden note',
            'waypoints_people_title' => 'People heading',
            'waypoints_sit_first' => 'Sit first',
            'waypoints_join_first' => 'Join first',
            'waypoints_guest_rest' => 'Guest sit line',
            'waypoints_note_one' => 'One note',
            'waypoints_note_many' => 'Several notes',
            'waypoints_pinned' => 'Pinned',
            'waypoints_last_note' => 'Last note',
        ],
        'Reading Room' => [
            'reading_title' => 'Title',
            'reading_intro' => 'Introduction',
        ],
        'Out There' => [
            'out_there_title' => 'Title',
            'out_there_form_title' => 'Story heading',
            'out_there_prompt' => 'Story prompt',
            'out_there_legacy_help' => 'Older story help',
            'out_there_body_label' => 'Story label',
            'out_there_did' => 'What I did',
            'out_there_expected' => 'What I expected',
            'out_there_happened' => 'What happened',
            'out_there_again' => 'Would I do it again',
            'out_there_guest' => 'Guest line',
            'out_there_after' => 'Replies heading',
            'out_there_reply_label' => 'Reply label',
            'out_there_hidden' => 'Hidden note',
        ],
        'Contact' => [
            'contact_headline' => 'Heading',
            'contact_card_title' => 'Card title',
            'contact_body' => 'Card note',
            'contact_name' => 'Name label',
            'contact_email' => 'Email label',
            'contact_note' => 'Note label',
            'contact_thanks_title' => 'Thanks heading',
            'contact_thanks_body' => 'Thanks note',
            'contact_reach' => 'Reach line',
        ],
        'Founder Story' => [
            'about_heading' => 'Opening heading',
            'about_intro' => 'Opening',
            'about_founder_heading' => 'Founder heading',
            'about_founder_body' => 'Founder story',
            'about_belief_heading' => 'Belief heading',
            'about_belief_body' => 'Belief',
            'about_hello_heading' => 'Hello heading',
            'about_hello_body' => 'Hello note',
            'about_close_heading' => 'Closing heading',
            'about_close_body' => 'Closing line',
            'about_image_alt' => 'Picture description',
            'label_founder' => 'Founder label',
        ],
        'Footer' => [
            'footer_line' => 'Footer line',
            'footer_note' => 'Second footer line',
        ],
        'Policies' => [
            'policy_privacy_label' => 'Privacy link',
            'policy_privacy_body' => 'Privacy text',
            'policy_terms_label' => 'House notes link',
            'policy_terms_body' => 'House notes text',
        ],
        'Buttons & CTAs' => [
            'hero_primary' => 'Homepage primary button',
            'hero_secondary' => 'Homepage secondary button',
            'cta_explore_seeds' => 'Explore Seeds',
            'cta_take_trip' => 'Take The Trip',
            'cta_share_story' => 'Share Your Story',
            'cta_pull_chair' => 'Pull Up A Chair',
            'cta_read_story' => 'Read The Story',
            'cta_learn_more' => 'Learn More',
            'cta_tell_story' => 'Tell the story',
            'cta_put_by_fire' => 'Put it by the fire',
            'cta_start_discussion' => 'Start the discussion',
            'cta_share_note' => 'Share a note',
            'cta_share' => 'Share it',
            'cta_sit' => 'Sit with this waypoint',
            'cta_leave_chair' => 'Leave this chair',
            'cta_plant_seed' => 'Plant this seed',
            'cta_ask_intro' => 'Ask for an introduction',
            'cta_offer_skill' => 'Offer or request a skill',
            'cta_join' => 'Join Go Solo',
            'cta_log_in' => 'Log in',
            'cta_send_report' => 'Send a report',
            'cta_remove_note' => 'Remove this note',
            'cta_remove_discussion' => 'Remove this discussion',
            'cta_logout' => 'Log out',
            'cta_tend' => 'Tend this garden',
            'cta_notes' => 'Notes',
            'cta_account' => 'Account',
            'cta_leave_note' => 'Leave the note',
            'cta_save' => 'Save',
            'cta_send_note' => 'Send the note',
            'cta_reset' => 'Send a reset note',
            'cta_back_home' => 'Back home',
            'cta_save_email' => 'Save email',
            'cta_change_password' => 'Change password',
            'cta_save_password' => 'Save the password',
            'cta_delete_account' => 'Delete my account',
            'cta_save_garden' => 'Save the garden',
            'cta_wake' => 'Wake it',
            'cta_rest' => 'Let it rest',
            'cta_set_down' => 'Set it down',
            'cta_set_this' => 'Set this down',
            'cta_plant_it' => 'Plant it',
            'seeds_go_profile' => 'Go to your profile',
            'editor_list' => 'List',
            'editor_quote' => 'Quote',
            'editor_link' => 'Link',
        ],
        'Empty States' => [
            'out_there_empty' => 'Out There explanation',
            'campfire_waiting' => 'Campfire waiting line',
            'campfire_empty' => 'Campfire explanation',
            'empty_campfire_replies' => 'Campfire replies',
            'empty_story_replies' => 'Story replies',
            'empty_discussion' => 'Waypoint discussion',
            'empty_discussion_replies' => 'Discussion replies',
            'empty_notes' => 'Notes',
            'empty_people' => 'Empty chairs',
            'empty_food' => 'Food for Thought',
            'empty_waypoints' => 'No waypoints yet',
            'empty_chair' => 'No chair chosen',
            'empty_planted' => 'Nothing planted',
            'empty_requests' => 'No requests',
            'empty_offers' => 'No offers',
            'empty_rhythm' => 'Still finding a rhythm',
            'empty_stories' => 'No stories brought back',
            'empty_bio' => 'Bio waiting',
            'empty_shelves' => 'Reading room shelves',
            'empty_shelf' => 'One shelf',
            'empty_notices' => 'No notes yet',
            'note_hidden' => 'Hidden from the house',
        ],
        'System Messages' => [
            'msg_seed_planted' => 'Seed planted',
            'msg_introduction' => 'Introduction asked',
            'msg_title_enough' => 'Title is enough',
            'msg_on_board' => 'On the board',
            'msg_report_needs' => 'Report needs words',
            'msg_report' => 'Report received',
            'msg_joined' => 'Joined',
            'msg_reset' => 'Reset note sent',
            'msg_password' => 'Password in place',
            'msg_garden' => 'Garden saved',
            'msg_email' => 'Email saved',
            'msg_password_changed' => 'Password changed',
            'msg_story' => 'Story published',
            'msg_campfire' => 'Campfire published',
            'msg_discussion' => 'Discussion created',
            'msg_few_words' => 'A few words are enough',
            'msg_story_needs' => 'Story needs more',
            'msg_campfire_needs' => 'Campfire needs more',
            'msg_discussion_needs' => 'Discussion needs more',
            'msg_not_saved' => 'Writing did not save',
            'msg_come_in' => 'Come in first',
            'msg_words_saved' => 'Words saved',
            'msg_picture_failed' => 'Picture failed',
            'msg_picture_size' => 'Picture too large',
            'msg_picture_type' => 'Picture type',
            'msg_contact_needs' => 'Contact form needs more',
            'missing_title' => 'Missing page heading',
            'missing_body' => 'Missing page text',
        ],
        'Conversations' => [
            'talk_communication' => 'Communication Preferences',
            'talk_pref_intro' => 'Preference introduction',
            'talk_pref_prompt' => 'Review prompt',
            'talk_pref_anyone' => 'Anyone',
            'talk_pref_anyone_note' => 'Anyone note',
            'talk_pref_context' => 'Shared context',
            'talk_pref_recommended' => 'Recommended',
            'talk_pref_context_note' => 'Shared context note',
            'talk_pref_none' => 'No private conversations at this time',
            'talk_pref_none_note' => 'Paused note',
            'talk_pref_save' => 'Save Communication Preference',
            'talk_join_heading' => 'Join heading',
            'talk_edit_link' => 'Garden link',
            'talk_heading' => 'Private conversation',
            'talk_request_heading' => 'Private Conversation Request',
            'talk_accept' => 'Accept Conversation',
            'talk_decline' => 'Not at This Time',
            'talk_block' => 'Block',
            'talk_not_opened' => 'Conversation was not opened',
            'talk_paused_other' => 'Not accepting at this time',
            'talk_paused_self' => 'Paused, own view',
            'talk_paused_block' => 'Set aside',
            'talk_active' => 'Active conversations',
            'talk_empty' => 'No conversations yet',
            'talk_requests' => 'Conversation requests',
            'talk_waiting' => 'Waiting',
            'talk_request_with' => 'Request is with them',
            'talk_blocks' => 'Set aside heading',
            'talk_unblock' => 'Welcome private conversations again',
            'talk_offer' => 'Offer Support',
            'talk_interested' => "I'm Interested",
            'talk_hello' => 'Say Hello',
            'talk_with' => 'With {name}',
            'talk_opening' => 'Short note',
            'talk_opening_hint' => 'Short note hint',
            'talk_send_request' => 'Send the request',
            'talk_context_seed' => 'Seed label',
            'talk_context_skill' => 'Skill Swap label',
            'talk_context_waypoint' => 'Waypoint label',
            'talk_context_introduction' => 'Introduction label',
            'talk_context_campfire' => 'Campfire label',
            'talk_context_story' => 'Out There label',
            'talk_context_member' => 'Member label',
            'talk_because' => 'Introduced because',
            'talk_participants' => 'Participants',
            'talk_similar' => 'Similar path',
            'talk_line_seed' => 'Offered support, use {name}',
            'talk_line_skill' => 'Interested in a swap, use {name}',
            'talk_line_public' => 'After a public note, use {name}',
            'talk_line_hello' => 'Said hello, use {name}',
            'talk_closed' => 'Conversation resting',
            'talk_held' => 'Conversations resting',
            'talk_body' => 'Note label',
            'talk_send' => 'Leave a note',
            'talk_notice_request' => 'Request notice, use {name}',
            'talk_notice_open' => 'Opened notice, use {name}',
            'talk_notice_note' => 'Note notice, use {name}',
            'talk_notice_resting' => 'Rested notice',
            'talk_notice_closed' => 'Not opened notice',
            'msg_talk_pref' => 'Preference saved',
            'msg_talk_choice' => 'Choice required',
            'msg_talk_note' => 'Note required',
            'msg_talk_request' => 'Request sent',
            'msg_talk_accepted' => 'Conversation accepted',
            'msg_talk_set_aside' => 'Request set aside',
            'msg_talk_unavailable' => 'Conversation not available',
        ],
        'Life' => [
            'life_seed_growing' => 'Growing',
            'life_seed_hold' => 'On Hold',
            'life_seed_grown' => 'Grown',
            'life_seed_archived' => 'Archived',
            'life_seed_growing_note' => 'Growing note',
            'life_seed_hold_note' => 'On hold note',
            'life_seed_grown_note' => 'Grown note',
            'life_seed_archived_note' => 'Archived note',
            'life_seed_mark_growing' => 'Mark growing',
            'life_seed_mark_hold' => 'Place on hold',
            'life_seed_mark_grown' => 'Mark grown',
            'life_seed_archive' => 'Archive seed',
            'life_seed_resume' => 'Resume seed',
            'life_seed_restore' => 'Restore seed',
            'life_seed_confirm' => 'Confirm seed change',
            'life_seed_reflect' => 'Seed reflection',
            'life_seed_reflect_help' => 'Seed reflection help',
            'life_seed_visibility' => 'Grown visibility',
            'life_seed_garden' => 'Visible in garden',
            'life_seed_private' => 'Only me',
            'life_seed_context' => 'Seed context, use {status}',
            'life_seed_open' => 'Open seed',
            'life_skill_open' => 'Skill open',
            'life_skill_progress' => 'Skill in progress',
            'life_skill_paused' => 'Skill paused',
            'life_skill_completed' => 'Skill completed',
            'life_skill_archived' => 'Skill archived',
            'life_skill_pause' => 'Pause interest',
            'life_skill_resume' => 'Resume skill',
            'life_skill_complete' => 'Complete skill',
            'life_skill_archive' => 'Archive skill',
            'life_skill_restore' => 'Restore skill',
            'life_skill_end' => 'End my part',
            'life_skill_rejoin' => 'Rejoin skill',
            'life_skill_pause_note' => 'Pause note',
            'life_skill_complete_note' => 'Complete note',
            'life_skill_archive_note' => 'Archive skill note',
            'life_skill_confirm' => 'Confirm skill change',
            'life_skill_context' => 'Skill context, use {status}',
            'life_skill_mine' => 'Your skill swaps',
            'life_intro_close' => 'Close introduction',
            'life_intro_close_note' => 'Close introduction note',
            'life_intro_accept' => 'Accept introduction',
            'life_intro_decline' => 'Decline introduction',
            'life_intro_feedback' => 'Introduction feedback',
            'life_intro_helpful' => 'Helpful',
            'life_intro_fit' => 'Not the fit',
            'life_intro_changed' => 'Circumstances changed',
            'life_intro_unsay' => 'Rather not say',
            'life_intro_closed_line' => 'Introduction closed',
            'life_intro_waiting' => 'Waiting',
            'life_intro_open' => 'Introduction open',
            'life_intro_needs' => 'Needs a response',
            'life_intro_opened' => 'Introduction opened notice',
            'life_talk_archive' => 'Archive conversation',
            'life_talk_restore' => 'Restore conversation',
            'life_talk_mute' => 'Mute conversation',
            'life_talk_unmute' => 'Unmute conversation',
            'life_talk_close' => 'Close conversation',
            'life_talk_close_note' => 'Close conversation note',
            'life_talk_reopen' => 'Reopen conversation',
            'life_talk_served' => 'Served its purpose',
            'life_talk_served_note' => 'Served note',
            'life_talk_forget' => 'Clear served label',
            'life_talk_closed' => 'Conversation closed',
            'life_talk_archived' => 'Archived conversations',
            'life_talk_closed_heading' => 'Closed conversations',
            'life_space_heading' => 'Taking a little space',
            'life_space_body' => 'Space introduction',
            'life_space_talk' => 'Pause conversations',
            'life_space_talk_note' => 'Pause conversations note',
            'life_space_intro' => 'Pause introductions',
            'life_space_intro_note' => 'Pause introductions note',
            'life_space_seed' => 'Pause seed support',
            'life_space_seed_note' => 'Pause seed support note',
            'life_space_skill' => 'Pause skill interest',
            'life_space_skill_note' => 'Pause skill interest note',
            'life_space_notices' => 'Mute community notices',
            'life_space_notices_note' => 'Mute notices note',
            'life_space_save' => 'Save space settings',
            'life_season_heading' => 'Life season heading',
            'life_season_help' => 'Life season help',
            'life_season_clear' => 'Clear life season',
            'life_season_public' => 'Season in garden',
            'life_season_private' => 'Season only me',
            'life_season_save' => 'Save life season',
            'life_path_heading' => 'Path heading',
            'life_path_hide' => 'Hide from garden',
            'life_path_show' => 'Show in garden',
            'life_path_hidden' => 'Hidden label',
            'life_path_growing' => 'Path growing',
            'life_path_hold' => 'Path on hold',
            'life_path_grown' => 'Path grown',
            'life_path_skills_offered' => 'Path skills offered',
            'life_path_skills_requested' => 'Path skills requested',
            'life_path_skills_done' => 'Path skills completed',
            'life_path_waypoints' => 'Path waypoints',
            'life_path_stories' => 'Path stories',
            'life_path_campfire' => 'Path campfire',
            'life_path_intro' => 'Path introductions',
            'life_path_reflections' => 'Path reflections',
            'life_outcome_invite' => 'Outcome invitation',
            'life_outcome_prompts' => 'Outcome prompts',
            'life_outcome_private' => 'Keep private',
            'life_outcome_private_note' => 'Private note',
            'life_outcome_garden' => 'Show in garden',
            'life_outcome_garden_note' => 'Garden note',
            'life_outcome_offer' => 'Offer to steward',
            'life_outcome_offer_note' => 'Offer note',
            'life_outcome_save' => 'Save outcome',
            'life_outcome_withdraw' => 'Withdraw outcome',
            'life_outcome_preview' => 'Outcome preview',
            'life_outcome_names' => 'Do not name people',
            'life_outcome_permit' => 'Confirm sharing',
            'life_outcome_permission' => 'Permission needed',
            'life_outcome_notice' => 'Steward outcome notice',
            'life_trust_heading' => 'Trust heading',
            'life_trust_seeds' => 'Helped with seeds',
            'life_trust_skill' => 'Completed a skill swap',
            'life_trust_story' => 'Shared a story',
            'life_trust_since' => 'Member since, use {date}',
            'life_trust_show' => 'Show participation',
            'life_trust_show_note' => 'Trust note',
            'life_trust_save' => 'Save trust choice',
            'life_optional' => 'Optional',
            'life_empty_grown' => 'No grown seeds',
            'life_empty_skills' => 'No closed skill swaps',
            'life_empty_path' => 'Empty path',
            'life_empty_outcomes' => 'Empty outcomes',
            'life_empty_intro' => 'No introductions',
            'life_empty_offered' => 'No offered stories',
            'life_empty_desk' => 'Nothing needs a look',
            'life_empty_seasons' => 'Season summary empty',
            'life_msg_status' => 'Status saved',
            'life_msg_unavailable' => 'Change unavailable',
            'life_msg_confirm' => 'Confirmation needed',
            'life_msg_space' => 'Space saved',
            'life_msg_season' => 'Season saved',
            'life_msg_trust' => 'Trust choice saved',
            'life_msg_outcome' => 'Outcome saved',
            'life_msg_withdraw' => 'Consent withdrawn',
            'life_msg_intro_paused' => 'Introduction paused',
            'life_report_category' => 'Report category',
            'life_report_unset' => 'No category',
            'life_report_concern' => 'Concern',
            'life_report_safety' => 'Safety',
            'life_report_other' => 'Other',
            'life_desk_community' => 'Community desk',
            'life_desk_ready' => 'Import life update',
            'life_desk_seeds' => 'Community seeds',
            'life_desk_skills' => 'Community skills',
            'life_desk_same' => 'Community introductions',
            'life_desk_waypoints' => 'Community waypoints',
            'life_desk_reports' => 'Community reports',
            'life_desk_outcomes' => 'Community outcomes',
            'life_desk_pauses' => 'Paused accounts',
            'life_desk_links' => 'Content relationships',
            'life_desk_seasons' => 'Life seasons',
            'life_desk_overview' => 'Community overview',
            'life_desk_look' => 'Needs a look',
            'life_desk_missing' => 'Missing record',
            'life_desk_restricted' => 'Restricted accounts',
            'life_filter_search' => 'Search',
            'life_filter_status' => 'Status',
            'life_filter_type' => 'Type',
            'life_filter_from' => 'From',
            'life_filter_to' => 'To',
            'life_filter_apply' => 'Apply filters',
            'life_filter_any' => 'Any',
            'life_filter_page' => 'Page',
            'life_filter_prev' => 'Previous page',
            'life_filter_next' => 'Next page',
        ],
        'Pins' => [
            'pin_welcome' => 'Welcome',
            'pin_start' => 'Start here',
            'pin_by' => 'Pinned by steward',
            'pin_featured' => 'Featured reading',
            'pin_hide' => 'I have read this',
            'pin_hide_welcome' => 'Hide welcome',
            'pin_show' => 'Show this again',
            'pin_aside' => 'Welcome set aside',
            'pin_pin' => 'Pin post',
            'pin_unpin' => 'Unpin post',
            'pin_replace' => 'Replace pinned post',
            'pin_feature' => 'Feature resource',
            'pin_clear' => 'Clear featured resource',
            'pin_order' => 'Order',
            'pin_save_order' => 'Save order',
            'pin_feature_note' => 'Featured note',
            'pin_edit' => 'Edit pinned writing',
            'pin_edit_save' => 'Save pinned writing',
            'pin_edit_note' => 'Edit note',
            'pin_back' => 'Back',
            'pin_import' => 'Import pins update',
            'pin_msg' => 'Welcome updated',
            'pin_msg_hide' => 'Welcome set aside',
            'pin_msg_show' => 'Welcome restored',
            'pin_msg_edit' => 'Writing saved',
            'pin_unavailable' => 'Pin unavailable',
            'pin_needs_words' => 'Words needed',
        ],
        'Path' => [
            'path_culture' => 'Choose by what they are building',
            'path_awkward' => 'Awkward moments',
            'path_picture' => 'Shared experience',
            'path_question' => 'The question',
            'path_room_name' => 'Chair name',
            'path_room_days' => 'Days a chair stays open, from 3 to 60',
            'path_room_opened' => 'Chair opened',
            'path_room_until' => 'Chair lasts until, use {date}',
            'path_room_kept_wait' => 'Waiting for both to keep the chair',
            'path_room_kept' => 'Chair kept',
            'path_keep' => 'Keep the chair',
            'path_keep_notice' => 'Keep notice, use {name}',
            'path_expired' => 'Chair time has passed',
            'path_growing' => 'Growing',
            'path_waypoint' => 'Waypoint',
            'path_looking' => 'Looking for',
            'path_offers' => 'Offers',
            'path_pace' => 'Pace',
            'path_pace_open' => 'Pace not set',
            'path_shows' => 'Shows up',
            'path_show_campfire' => 'Campfire count, use {count}',
            'path_show_chair' => 'Waypoint count, use {count}',
            'path_bio_note' => 'A few words note',
            'path_empty' => 'Portrait still settling',
            'path_skill_invited' => 'Skill introduction, use {name}',
            'path_skill_note' => 'Skill chair note',
            'path_unavailable' => 'Path unavailable',
        ],
        'Navigation' => [
            'nav_about' => 'About',
            'nav_seeds' => 'Seeds',
            'nav_out_there' => 'Out There',
            'nav_campfire' => 'Campfire',
            'nav_waypoints' => 'Waypoints',
            'nav_reading' => 'Reading Room',
            'nav_contact' => 'Contact',
            'nav_join' => 'Join',
            'nav_login' => 'Log In',
            'nav_profile' => 'Profile',
            'nav_steward' => 'Steward',
            'skip_content' => 'Skip to content',
        ],
        'Garden & Account' => [
            'garden_kicker_mine' => 'My garden label',
            'garden_kicker_other' => 'Someone else\'s garden',
            'garden_member' => 'Nameless member',
            'garden_bio' => 'Bio heading',
            'garden_similar' => 'Similar path heading',
            'garden_match' => 'Introduction line, use {name}',
            'garden_note_label' => 'Note label',
            'garden_skill' => 'Skill swap heading',
            'garden_skill_match' => 'Skill swap line, use {name}',
            'garden_waypoints' => 'Waypoints heading',
            'garden_growing' => 'Growing heading',
            'garden_resting' => 'Resting',
            'garden_open_help' => 'Open to help',
            'garden_help' => 'Help growing heading',
            'garden_offers' => 'Happy to help heading',
            'garden_support' => 'Support heading',
            'garden_frequency' => 'Contact frequency heading',
            'garden_frequency_any' => 'Frequency not set',
            'garden_style' => 'Check-in heading',
            'garden_style_any' => 'Style not set',
            'garden_stories' => 'Stories heading',
            'garden_hidden' => 'Hidden',
            'garden_warning' => 'Steward note heading',
            'label_report' => 'Report label',
            'label_report_note' => 'Report a note',
            'label_title' => 'Title',
            'label_write' => 'Write here',
            'label_photo' => 'Photograph on a story',
            'label_photo_alt' => 'Photograph description',
            'label_email' => 'Email',
            'label_password' => 'Password',
            'label_name' => 'Name',
            'label_note' => 'Note',
            'label_bio' => 'Bio',
            'account_title' => 'Account heading',
            'account_password' => 'Password heading',
            'account_current' => 'Current password',
            'account_new' => 'New password',
            'account_close' => 'Close account heading',
            'account_close_body' => 'Close account text',
            'account_confirm' => 'Delete confirmation',
            'join_title' => 'Join heading',
            'join_intro' => 'Join introduction',
            'join_call_you' => 'Name question',
            'join_password_hint' => 'Password hint',
            'join_have_chair' => 'Already have a chair',
            'login_title' => 'Log in heading',
            'login_intro' => 'Log in introduction',
            'login_forgot' => 'Forgot password',
            'login_new' => 'New here',
            'forgot_title' => 'Forgot heading',
            'forgot_intro' => 'Forgot introduction',
            'forgot_back' => 'Back to log in',
            'reset_title' => 'Reset heading',
            'reset_invalid' => 'Link finished',
            'reset_again' => 'Ask for another',
            'notices_title' => 'Notes heading',
            'notices_intro' => 'Notes introduction',
            'edit_title' => 'Tend heading',
            'edit_see' => 'See it as others do',
            'edit_location' => 'Location',
            'edit_show_location' => 'Show location',
            'edit_photo' => 'Photograph',
            'edit_remove_photo' => 'Remove photograph',
            'edit_tiny' => 'A tiny future',
            'edit_want_help' => 'I would like help',
            'edit_shelf' => 'From the shelf',
        ],
    ];
}

function settings_text_keys(): array
{
    return [
        'site_title' => 'Site title',
        'tagline' => 'Tagline',
        'logo_text' => 'Logo words',
        'founder_name' => 'Founder name',
        'founder_email' => 'Founder email',
        'email_reset_subject' => 'Password reset subject',
        'email_reset_body' => 'Password reset note',
    ];
}

function color_keys(): array
{
    return [
        'color_background' => 'Background',
        'color_ink' => 'Ink',
        'color_soft' => 'Soft text',
        'color_sage' => 'Sage',
        'color_clay' => 'Clay',
        'color_mist' => 'Mist',
        'color_card' => 'Cards',
    ];
}

function image_keys(): array
{
    return [
        'hero_image' => 'Homepage walk',
        'freedom_image' => 'Homepage at home',
        'out_there_image' => 'Out There',
        'campfire_image' => 'Campfire',
        'logo_image' => 'Small logo picture',
    ];
}

function long_setting(string $key, string $value): bool
{
    return str_contains($value, "\n")
        || str_contains($key, 'body')
        || str_contains($key, 'intro')
        || str_contains($key, 'prompt')
        || str_contains($key, 'policy_')
        || strlen($value) > 140;
}
