import type {
  CampfirePost,
  Comment,
  Membership,
  OutTherePost,
  Partnership,
  Profile,
  Reaction,
  SkillOffer,
  SkillRequest,
  UserSeed,
} from "@/lib/types";

const baseProfile = {
  email: "",
  avatarUrl: "",
  onboardingComplete: true,
  emailVerified: true,
  showLocation: true,
  showWaypoints: true,
  notifyReplies: false,
  notifyWaypoints: false,
  notifyCheckins: false,
};

export const communityProfiles: Profile[] = [
  {
    ...baseProfile,
    id: "mira",
    displayName: "Mira Chen",
    bio: "Photographer living alone in a bright apartment with a temperamental kettle. I take myself on small trips and then tell the truth about them.",
    location: "Lisbon",
    intentions: ["adventure", "curiosity"],
    interests: ["travel", "creativity", "walking"],
    createdAt: "2025-11-02T10:00:00.000Z",
  },
  {
    ...baseProfile,
    id: "jonah",
    displayName: "Jonah Ellis",
    bio: "New city, old habit of waiting for company before I cook. Learning to set the table anyway.",
    location: "Chicago",
    intentions: ["starting-over", "connection"],
    interests: ["cooking", "home-diy", "community"],
    createdAt: "2026-01-18T10:00:00.000Z",
  },
  {
    ...baseProfile,
    id: "asha",
    displayName: "Asha Reddy",
    bio: "Starting over in a smaller place with more quiet than I expected. I am interested in what grows when no one is watching.",
    location: "Manchester",
    intentions: ["starting-over", "curiosity"],
    interests: ["personal-growth", "books", "nature"],
    createdAt: "2026-02-04T10:00:00.000Z",
  },
  {
    ...baseProfile,
    id: "leo",
    displayName: "Leo Park",
    bio: "I walk, I read, and I talk to people at the edges of both. Looking for a life that feels spacious.",
    location: "Seoul",
    intentions: ["adventure", "meeting-people"],
    interests: ["books", "walking", "learning"],
    createdAt: "2025-09-12T10:00:00.000Z",
  },
  {
    ...baseProfile,
    id: "noor",
    displayName: "Noor Haddad",
    bio: "Building home systems that make living alone feel like a craft, not a gap.",
    location: "Amman",
    intentions: ["confidence", "first-time-alone"],
    interests: ["home-diy", "personal-growth", "cooking"],
    createdAt: "2026-03-01T10:00:00.000Z",
  },
  {
    ...baseProfile,
    id: "samira",
    displayName: "Samira Okonkwo",
    bio: "Pottery on Tuesdays. Museums when the week needs a different room. I go alone and stay longer than I planned.",
    location: "Brooklyn",
    intentions: ["adventure", "confidence"],
    interests: ["creativity", "community", "travel"],
    createdAt: "2025-12-09T10:00:00.000Z",
  },
];

export const communityMemberships: Membership[] = [
  { userId: "mira", waypointId: "solo-among-others", joinedAt: "2025-11-03T10:00:00.000Z" },
  { userId: "jonah", waypointId: "independence-lab", joinedAt: "2026-01-19T10:00:00.000Z" },
  { userId: "jonah", waypointId: "solo-among-others", joinedAt: "2026-02-02T10:00:00.000Z" },
  { userId: "asha", waypointId: "emotional-clarity", joinedAt: "2026-02-05T10:00:00.000Z" },
  { userId: "leo", waypointId: "emotional-clarity", joinedAt: "2025-09-13T10:00:00.000Z" },
  { userId: "leo", waypointId: "solo-among-others", joinedAt: "2025-10-01T10:00:00.000Z" },
  { userId: "noor", waypointId: "independence-lab", joinedAt: "2026-03-02T10:00:00.000Z" },
  { userId: "samira", waypointId: "solo-among-others", joinedAt: "2025-12-10T10:00:00.000Z" },
  { userId: "samira", waypointId: "emotional-clarity", joinedAt: "2026-01-08T10:00:00.000Z" },
];

export const communityUserSeeds: UserSeed[] = [
  {
    id: "us-mira-witness",
    userId: "mira",
    seedId: "one-witness",
    status: "active",
    goal: "Visit one new place each week and tell one person the truth about it.",
    startedAt: "2026-09-07T10:00:00.000Z",
    checkIns: [],
  },
  {
    id: "us-noor-hello",
    userId: "noor",
    seedId: "weekly-hello",
    status: "active",
    goal: "A Sunday note about the home system I actually used.",
    startedAt: "2026-09-14T10:00:00.000Z",
    checkIns: [],
  },
  {
    id: "us-jonah-meal",
    userId: "jonah",
    seedId: "meal-for-you",
    status: "active",
    goal: "",
    startedAt: "2026-09-20T10:00:00.000Z",
    checkIns: [
      {
        id: "ci-jonah-1",
        at: "2026-09-30T19:00:00.000Z",
        note: "The chicken was for me. I stayed at the table.",
      },
    ],
  },
];

export const communityPartnerships: Partnership[] = [
  {
    id: "p-mira-witness",
    seedId: "one-witness",
    seekerId: "mira",
    partnerId: null,
    goal: "Visit one new place each week and tell one person the truth about it.",
    status: "seeking",
    createdAt: "2026-09-07T10:00:00.000Z",
    checkIns: [],
  },
  {
    id: "p-noor-hello",
    seedId: "weekly-hello",
    seekerId: "noor",
    partnerId: null,
    goal: "A Sunday note about the home system I actually used.",
    status: "seeking",
    createdAt: "2026-09-14T10:00:00.000Z",
    checkIns: [],
  },
];

export const communityOffers: SkillOffer[] = [
  {
    id: "offer-mira",
    userId: "mira",
    skill: "Photography",
    description: "I can show you how I walk with a camera for an hour. No portfolio required.",
    createdAt: "2026-08-12T10:00:00.000Z",
  },
  {
    id: "offer-jonah",
    userId: "jonah",
    skill: "Cooking",
    description: "Weeknight meals for one that do not feel like leftovers.",
    createdAt: "2026-08-20T10:00:00.000Z",
  },
  {
    id: "offer-noor",
    userId: "noor",
    skill: "Home systems",
    description: "We will set up one tiny system, not a whole life overhaul.",
    createdAt: "2026-09-02T10:00:00.000Z",
  },
  {
    id: "offer-samira",
    userId: "samira",
    skill: "Studio companionship",
    description: "I am not a pottery teacher. I am a person who will go to the studio with you.",
    createdAt: "2026-09-09T10:00:00.000Z",
  },
];

export const communityRequests: SkillRequest[] = [
  {
    id: "request-leo",
    userId: "leo",
    skill: "Languages",
    description: "Looking for someone to practice spoken English or Korean, badly and kindly.",
    createdAt: "2026-09-11T10:00:00.000Z",
  },
  {
    id: "request-asha",
    userId: "asha",
    skill: "Budgeting",
    description: "I want a calm hour on money, not a lecture.",
    createdAt: "2026-09-16T10:00:00.000Z",
  },
  {
    id: "request-jonah",
    userId: "jonah",
    skill: "Gardening",
    description: "I have a window and no idea. Happy to trade dinner.",
    createdAt: "2026-09-18T10:00:00.000Z",
  },
];

export const communityStories: OutTherePost[] = [
  {
    id: "story-mira",
    authorId: "mira",
    title: "The museum on a Wednesday",
    whatDidYouDo:
      "I went to the tile museum alone after work and stayed until they started closing the rooms.",
    expecting: "I thought I would feel conspicuous and leave after twenty minutes.",
    actuallyHappened:
      "Nobody noticed me. I sat in front of one blue wall longer than I ever would with company. I wrote a sentence on a receipt.",
    wouldDoAgain: "yes",
    seedId: "museum-sentence",
    waypointId: "solo-among-others",
    createdAt: "2026-09-28T18:00:00.000Z",
  },
  {
    id: "story-jonah",
    authorId: "jonah",
    title: "The dinner I kept saving",
    whatDidYouDo:
      "I cooked the lemon chicken I only made when someone was visiting. I set one plate and ate at the table.",
    expecting: "I expected it to feel a little sad, like a rehearsal for a real evening.",
    actuallyHappened:
      "It felt like a normal evening that belonged to me. The sad part was how long I had waited.",
    wouldDoAgain: "yes",
    seedId: "meal-for-you",
    waypointId: "independence-lab",
    createdAt: "2026-09-30T20:00:00.000Z",
  },
  {
    id: "story-samira",
    authorId: "samira",
    title: "Pottery, and staying after the break",
    whatDidYouDo:
      "I took a Tuesday pottery class I had bookmarked for a year. I went straight from work and rode home with clay under my nails.",
    expecting: "I thought I would be bad, and that being bad would make me want to disappear.",
    actuallyHappened:
      "I was bad. The teacher was kind without making it a moment. Someone asked what I was making and I said a bowl, theoretically. We laughed and went back to our own clay.",
    wouldDoAgain: "maybe",
    seedId: "imperfect-making",
    waypointId: "solo-among-others",
    createdAt: "2026-09-22T21:00:00.000Z",
  },
  {
    id: "story-asha",
    authorId: "asha",
    title: "A walk with the podcast left at home",
    whatDidYouDo: "I walked the long way around the park with nothing in my ears.",
    expecting: "I expected my head to get loud.",
    actuallyHappened:
      "It did, for ten minutes. Then it got specific. I remembered a street from the city I left and did not try to turn it into a lesson.",
    wouldDoAgain: "yes",
    seedId: "walk-no-podcast",
    waypointId: "emotional-clarity",
    createdAt: "2026-10-01T16:00:00.000Z",
  },
  {
    id: "story-leo",
    authorId: "leo",
    title: "A train to a town with a good bakery",
    whatDidYouDo:
      "I bought a return ticket for Saturday and spent four hours in a town where I knew no one. I ate a bun standing up.",
    expecting: "I thought I would want to text someone the whole time, to prove I was doing it.",
    actuallyHappened:
      "I texted once, then put the phone away because the street was more interesting than the update.",
    wouldDoAgain: "yes",
    seedId: "ticket-for-one",
    waypointId: "emotional-clarity",
    createdAt: "2026-09-18T12:00:00.000Z",
  },
  {
    id: "story-noor",
    authorId: "noor",
    title: "The light I turn on first",
    whatDidYouDo:
      "I stopped trying to redesign my whole morning. I moved the lamp and the kettle onto the same counter and used that corner for seven days.",
    expecting: "I thought a real system would be bigger than a lamp.",
    actuallyHappened: "The small corner made the apartment feel like it was on my side.",
    wouldDoAgain: "yes",
    seedId: "morning-system",
    waypointId: "independence-lab",
    createdAt: "2026-09-25T08:00:00.000Z",
  },
];

export const communityCampfire: CampfirePost[] = [
  {
    id: "fire-mira-question",
    authorId: "mira",
    section: "general",
    kind: "question",
    title: "Do you tell people you are going alone?",
    body: "I am taking a weekend train and I keep rehearsing how I will answer if someone asks who I am meeting. I do not want a speech. I also do not want to apologize. What do you actually say?",
    waypointId: "solo-among-others",
    createdAt: "2026-09-27T11:00:00.000Z",
  },
  {
    id: "fire-jonah-chair",
    authorId: "jonah",
    section: "solo-living",
    kind: "daily-life",
    title: "The second chair",
    body: "I have a second chair at the table that I never sit in and never put away. Tonight I moved it to the desk. The room got quieter in a good way. Small report from the apartment.",
    waypointId: "independence-lab",
    seedId: "room-for-this-life",
    createdAt: "2026-09-29T21:30:00.000Z",
  },
  {
    id: "fire-asha-tuesday",
    authorId: "asha",
    section: "deep-thoughts",
    kind: "reflection",
    title: "Starting over is mostly unnamed hours",
    body: "I thought a new city would feel like a chapter. Mostly it feels like Tuesday. I am learning to trust Tuesdays. If you are in the middle of an unnamed stretch, I am here too.",
    waypointId: "emotional-clarity",
    createdAt: "2026-10-01T19:00:00.000Z",
  },
  {
    id: "fire-noor-week",
    authorId: "noor",
    section: "growing",
    kind: "challenge",
    title: "A week of one system",
    body: "Not a new life. One corner of the kitchen that makes morning less negotiated. I will be back in seven days with what happened, including if I ignored it.",
    waypointId: "independence-lab",
    seedId: "morning-system",
    createdAt: "2026-09-24T07:40:00.000Z",
  },
  {
    id: "fire-samira-stay",
    authorId: "samira",
    section: "general",
    kind: "celebration",
    title: "I stayed for the whole class",
    body: "That is the whole announcement. I did not leave at the break. I did not narrate it to anyone until now. It counts.",
    waypointId: "solo-among-others",
    seedId: "imperfect-making",
    outThereId: "story-samira",
    createdAt: "2026-09-22T22:10:00.000Z",
  },
  {
    id: "fire-leo-meal",
    authorId: "leo",
    section: "solo-living",
    kind: "thought",
    title: "Eating alone is not a waiting room",
    body: "I used to treat solo meals like the time before the real plan. Last night the meal was the plan. The soup was too salty. I would still go back.",
    waypointId: "solo-among-others",
    seedId: "table-for-one",
    createdAt: "2026-09-19T20:15:00.000Z",
  },
  {
    id: "fire-mira-sentence",
    authorId: "mira",
    section: "deep-thoughts",
    kind: "story",
    title: "The sentence I wrote on a receipt",
    body: "I am allowed to be a person in a room. I do not know if it is a good sentence. It was the true one.",
    waypointId: "emotional-clarity",
    seedId: "museum-sentence",
    outThereId: "story-mira",
    createdAt: "2026-09-28T19:20:00.000Z",
  },
  {
    id: "fire-asha-permission",
    authorId: "asha",
    section: "growing",
    kind: "question",
    title: "What are you no longer waiting for permission to try?",
    body: "I will go first: a weekend away with no occasion. Your turn, if you want it.",
    waypointId: "emotional-clarity",
    createdAt: "2026-10-02T09:00:00.000Z",
  },
];

export const communityComments: Comment[] = [
  {
    id: "comment-leo-mira",
    authorId: "leo",
    targetType: "campfire",
    targetId: "fire-mira-question",
    body: "I say just me, and then I ask them something. It ends the speech before it starts.",
    createdAt: "2026-09-27T14:00:00.000Z",
  },
  {
    id: "comment-samira-stay",
    authorId: "noor",
    targetType: "campfire",
    targetId: "fire-samira-stay",
    body: "Staying is a skill. I am glad you practiced it.",
    createdAt: "2026-09-23T08:10:00.000Z",
  },
  {
    id: "comment-jonah-noor",
    authorId: "jonah",
    targetType: "campfire",
    targetId: "fire-noor-week",
    body: "I am in for the kitchen-corner version. Lamp and kettle.",
    createdAt: "2026-09-24T18:00:00.000Z",
  },
  {
    id: "comment-noor-chair",
    authorId: "noor",
    targetType: "campfire",
    targetId: "fire-jonah-chair",
    body: "The second chair was telling a story you did not mean to keep. Moving it counts.",
    createdAt: "2026-09-30T08:20:00.000Z",
  },
];

export const communityReactions: Reaction[] = [
  { id: "r1", userId: "leo", targetType: "out-there", targetId: "story-mira", kind: "inspired" },
  { id: "r2", userId: "asha", targetType: "out-there", targetId: "story-mira", kind: "perspective" },
  { id: "r3", userId: "samira", targetType: "out-there", targetId: "story-jonah", kind: "relate" },
  { id: "r4", userId: "noor", targetType: "out-there", targetId: "story-jonah", kind: "inspired" },
  { id: "r5", userId: "mira", targetType: "out-there", targetId: "story-samira", kind: "inspired" },
  { id: "r6", userId: "jonah", targetType: "out-there", targetId: "story-asha", kind: "relate" },
  { id: "r7", userId: "asha", targetType: "out-there", targetId: "story-leo", kind: "inspired" },
  { id: "r8", userId: "leo", targetType: "out-there", targetId: "story-noor", kind: "perspective" },
];
